import type { FocalPoint, StudioMediaItem } from "./types";

function parseFocal(value: string): FocalPoint {
  const [xRaw, yRaw] = value.replace(/%/g, "").split(/\s+/);
  return { x: Number(xRaw), y: Number(yRaw) };
}

/**
 * Stage 4A Part 2 — synthetic concept catalogue.
 * Rendered only when NEXT_PUBLIC_ENABLE_SYNTHETIC_MEDIA=true.
 */
export const MEDIA_CATALOGUE: readonly StudioMediaItem[] = [
  {
    id: "home-hero-ai-concept",
    slot: "home.hero",
    status: "synthetic-preview",
    kind: "image",
    source: "ai-concept",
    consentStatus: "not-applicable-synthetic",
    src: "/media/synthetic-preview/home-hero-ai-concept.webp",
    width: 1672,
    height: 941,
    orientation: "landscape",
    aspectRatio: "16/9",
    mobileAspectRatio: "4/3",
    alt: "Conceptual coach-led functional training scene — AI concept preview, not a real Ankit’s Studio session",
    focalPoint: parseFocal("72% 50%"),
    tabletFocalPoint: parseFocal("70% 50%"),
    mobileFocalPoint: parseFocal("72% 48%"),
    motionTreatment: "hero-reveal",
    replacementPriority: "P0",
  },
  {
    id: "home-community-ai-concept",
    slot: "home.community",
    status: "synthetic-preview",
    kind: "image",
    source: "ai-concept",
    consentStatus: "not-applicable-synthetic",
    src: "/media/synthetic-preview/home-community-ai-concept.webp",
    width: 1536,
    height: 1168,
    orientation: "landscape",
    aspectRatio: "4/3",
    mobileAspectRatio: "4/3",
    alt: "Conceptual community coaching atmosphere — AI concept preview, anonymous subjects",
    focalPoint: parseFocal("50% 46%"),
    tabletFocalPoint: parseFocal("50% 46%"),
    mobileFocalPoint: parseFocal("50% 42%"),
    motionTreatment: "section-reveal",
    replacementPriority: "P1",
  },
  {
    id: "programme-functional-hero-ai-concept",
    slot: "programme.functional.hero",
    status: "synthetic-preview",
    kind: "image",
    source: "ai-concept",
    consentStatus: "not-applicable-synthetic",
    src: "/media/synthetic-preview/programme-functional-hero-ai-concept.webp",
    width: 1536,
    height: 1168,
    orientation: "landscape",
    aspectRatio: "4/3",
    mobileAspectRatio: "4/3",
    alt: "Conceptual functional training movement — AI concept preview",
    focalPoint: parseFocal("52% 45%"),
    tabletFocalPoint: parseFocal("52% 44%"),
    mobileFocalPoint: parseFocal("52% 40%"),
    motionTreatment: "hero-reveal",
    programme: "functional-training",
    replacementPriority: "P0",
  },
  {
    id: "programme-functional-action-ai-concept",
    slot: "programme.functional.action",
    status: "synthetic-preview",
    kind: "image",
    source: "ai-concept",
    consentStatus: "not-applicable-synthetic",
    src: "/media/synthetic-preview/programme-functional-action-ai-concept.webp",
    width: 1536,
    height: 1168,
    orientation: "landscape",
    aspectRatio: "4/3",
    mobileAspectRatio: "4/3",
    alt: "Conceptual functional training action detail — AI concept preview",
    focalPoint: parseFocal("55% 48%"),
    tabletFocalPoint: parseFocal("55% 48%"),
    mobileFocalPoint: parseFocal("55% 44%"),
    motionTreatment: "section-reveal",
    programme: "functional-training",
    replacementPriority: "P1",
  },
  {
    id: "programme-zumba-hero-ai-concept",
    slot: "programme.zumba.hero",
    status: "synthetic-preview",
    kind: "image",
    source: "ai-concept",
    consentStatus: "not-applicable-synthetic",
    src: "/media/synthetic-preview/programme-zumba-hero-ai-concept.webp",
    width: 1536,
    height: 1168,
    orientation: "landscape",
    aspectRatio: "4/3",
    mobileAspectRatio: "4/3",
    alt: "Conceptual Zumba group energy — AI concept preview, not a real class photo",
    focalPoint: parseFocal("50% 42%"),
    tabletFocalPoint: parseFocal("50% 42%"),
    mobileFocalPoint: parseFocal("50% 38%"),
    motionTreatment: "hero-reveal",
    programme: "zumba",
    replacementPriority: "P0",
  },
  {
    id: "programme-yoga-hero-ai-concept",
    slot: "programme.yoga.hero",
    status: "synthetic-preview",
    kind: "image",
    source: "ai-concept",
    consentStatus: "not-applicable-synthetic",
    src: "/media/synthetic-preview/programme-yoga-hero-ai-concept.webp",
    width: 1536,
    height: 1168,
    orientation: "landscape",
    aspectRatio: "4/3",
    mobileAspectRatio: "4/3",
    alt: "Conceptual yoga practice atmosphere — AI concept preview",
    focalPoint: parseFocal("50% 45%"),
    tabletFocalPoint: parseFocal("50% 45%"),
    mobileFocalPoint: parseFocal("50% 42%"),
    motionTreatment: "hero-reveal",
    programme: "yoga",
    replacementPriority: "P0",
  },
  {
    id: "programme-dance-hero-ai-concept",
    slot: "programme.dance.hero",
    status: "synthetic-preview",
    kind: "image",
    source: "ai-concept",
    consentStatus: "not-applicable-synthetic",
    src: "/media/synthetic-preview/programme-dance-hero-ai-concept.webp",
    width: 1536,
    height: 1168,
    orientation: "landscape",
    aspectRatio: "4/3",
    mobileAspectRatio: "4/3",
    alt: "Conceptual adult dance movement — AI concept preview",
    focalPoint: parseFocal("53% 42%"),
    tabletFocalPoint: parseFocal("53% 42%"),
    mobileFocalPoint: parseFocal("53% 38%"),
    motionTreatment: "hero-reveal",
    programme: "adult-dance",
    replacementPriority: "P0",
  },
  {
    id: "programme-wedding-hero-ai-concept",
    slot: "programme.wedding.hero",
    status: "synthetic-preview",
    kind: "image",
    source: "ai-concept",
    consentStatus: "not-applicable-synthetic",
    src: "/media/synthetic-preview/programme-wedding-hero-ai-concept.webp",
    width: 1536,
    height: 1168,
    orientation: "landscape",
    aspectRatio: "4/3",
    mobileAspectRatio: "4/3",
    alt: "Conceptual wedding choreography rehearsal — AI concept preview, not real clients",
    focalPoint: parseFocal("54% 44%"),
    tabletFocalPoint: parseFocal("54% 44%"),
    mobileFocalPoint: parseFocal("54% 40%"),
    motionTreatment: "hero-reveal",
    programme: "wedding-choreography",
    replacementPriority: "P0",
  },
  {
    id: "programme-home-pt-hero-ai-concept",
    slot: "programme.home-pt.hero",
    status: "synthetic-preview",
    kind: "image",
    source: "ai-concept",
    consentStatus: "not-applicable-synthetic",
    src: "/media/synthetic-preview/programme-home-pt-hero-ai-concept.webp",
    width: 1536,
    height: 1168,
    orientation: "landscape",
    aspectRatio: "4/3",
    mobileAspectRatio: "4/3",
    alt: "Conceptual home personal training atmosphere — AI concept preview, not a real customer home",
    focalPoint: parseFocal("50% 48%"),
    tabletFocalPoint: parseFocal("50% 48%"),
    mobileFocalPoint: parseFocal("50% 44%"),
    motionTreatment: "hero-reveal",
    programme: "home-personal-training",
    replacementPriority: "P1",
  },
  {
    id: "programme-online-hero-ai-concept",
    slot: "programme.online.hero",
    status: "synthetic-preview",
    kind: "image",
    source: "ai-concept",
    consentStatus: "not-applicable-synthetic",
    src: "/media/synthetic-preview/programme-online-hero-ai-concept.webp",
    width: 1536,
    height: 1168,
    orientation: "landscape",
    aspectRatio: "4/3",
    mobileAspectRatio: "4/3",
    alt: "Conceptual remote training atmosphere — AI concept preview, not a real Ankit’s Studio session",
    /* Bias toward training subject; keep generated laptop UI out of critical crop */
    focalPoint: parseFocal("68% 42%"),
    tabletFocalPoint: parseFocal("66% 44%"),
    mobileFocalPoint: parseFocal("70% 40%"),
    motionTreatment: "hero-reveal",
    programme: "online-training",
    replacementPriority: "P1",
  },
  {
    id: "about-community-ai-concept",
    slot: "about.community",
    status: "synthetic-preview",
    kind: "image",
    source: "ai-concept",
    consentStatus: "not-applicable-synthetic",
    src: "/media/synthetic-preview/about-community-ai-concept.webp",
    width: 1536,
    height: 1168,
    orientation: "landscape",
    aspectRatio: "4/3",
    mobileAspectRatio: "4/3",
    alt: "Conceptual studio community atmosphere — AI concept preview, anonymous subjects",
    focalPoint: parseFocal("50% 44%"),
    tabletFocalPoint: parseFocal("50% 44%"),
    mobileFocalPoint: parseFocal("50% 40%"),
    motionTreatment: "section-reveal",
    replacementPriority: "P1",
  },
  {
    id: "locations-atmosphere-ai-concept",
    slot: "locations.atmosphere",
    status: "synthetic-preview",
    kind: "image",
    source: "ai-concept",
    consentStatus: "not-applicable-synthetic",
    src: "/media/synthetic-preview/locations-atmosphere-ai-concept.webp",
    width: 1536,
    height: 1168,
    orientation: "landscape",
    aspectRatio: "16/9",
    mobileAspectRatio: "4/3",
    alt: "Conceptual neighbourhood studio atmosphere — AI concept preview, not a specific branch",
    /* Floor/plant band only — wall emblem must not read as studio branding */
    focalPoint: parseFocal("55% 88%"),
    tabletFocalPoint: parseFocal("55% 86%"),
    mobileFocalPoint: parseFocal("58% 90%"),
    motionTreatment: "section-reveal",
    replacementPriority: "P2",
  },
] as const;

export function getCatalogueItem(slotKey: string): StudioMediaItem | undefined {
  return MEDIA_CATALOGUE.find((item) => item.slot === slotKey);
}
