import type { FocalPoint, StudioMediaItem } from "./types";

function parseFocal(value: string): FocalPoint {
  const [xRaw, yRaw] = value.replace(/%/g, "").split(/\s+/);
  return { x: Number(xRaw), y: Number(yRaw) };
}

const ILLUSTRATIVE = {
  status: "illustrative-ai" as const,
  source: "ai-generated-illustration" as const,
  consentStatus: "not-applicable-ai" as const,
  replacementStatus: "replace-after-owner-photoshoot" as const,
};

/**
 * Owner-approved interim illustrative catalogue — Stage Prompt 3 (12 Aug 2026).
 * Renders in public production without NEXT_PUBLIC_ENABLE_SYNTHETIC_MEDIA.
 * Historical Stage 4A synthetic-preview policy remains in docs for reference.
 */
export const MEDIA_CATALOGUE: readonly StudioMediaItem[] = [
  {
    id: "home-hero-ai-concept",
    slot: "home.hero",
    ...ILLUSTRATIVE,
    kind: "image",
    src: "/media/synthetic-preview/home-hero-v2.webp",
    width: 1376,
    height: 768,
    orientation: "landscape",
    aspectRatio: "16/9",
    mobileAspectRatio: "4/3",
    alt: "Illustrative athlete training with battle ropes in a dark studio",
    focalPoint: parseFocal("72% 30%"),
    tabletFocalPoint: parseFocal("70% 34%"),
    mobileFocalPoint: parseFocal("65% 38%"),
    motionTreatment: "hero-reveal",
    replacementPriority: "P0",
  },
  {
    id: "home-community-ai-concept",
    slot: "home.community",
    ...ILLUSTRATIVE,
    kind: "image",
    src: "/media/synthetic-preview/home-community-ai-concept.webp",
    width: 1536,
    height: 1168,
    orientation: "landscape",
    aspectRatio: "4/3",
    mobileAspectRatio: "4/3",
    alt: "Illustrative group coaching atmosphere with anonymous participants",
    focalPoint: parseFocal("50% 46%"),
    tabletFocalPoint: parseFocal("50% 46%"),
    mobileFocalPoint: parseFocal("50% 42%"),
    motionTreatment: "section-reveal",
    replacementPriority: "P1",
  },
  {
    id: "programme-functional-hero-ai-concept",
    slot: "programme.functional.hero",
    ...ILLUSTRATIVE,
    kind: "image",
    src: "/media/synthetic-preview/programme-functional-hero-ai-concept.webp",
    width: 1536,
    height: 1168,
    orientation: "landscape",
    aspectRatio: "4/3",
    mobileAspectRatio: "4/3",
    alt: "Illustrative functional training movement with battle ropes",
    focalPoint: parseFocal("52% 45%"),
    tabletFocalPoint: parseFocal("52% 44%"),
    mobileFocalPoint: parseFocal("52% 40%"),
    motionTreatment: "hero-reveal",
    programme: "functional-training",
    replacementPriority: "P0",
  },
  {
    id: "programme-functional-action-ai-concept",
    slot: "programme.functional.action",
    ...ILLUSTRATIVE,
    kind: "image",
    src: "/media/synthetic-preview/programme-functional-action-ai-concept.webp",
    width: 1536,
    height: 1168,
    orientation: "landscape",
    aspectRatio: "4/3",
    mobileAspectRatio: "4/3",
    alt: "Illustrative functional training action detail",
    focalPoint: parseFocal("55% 48%"),
    tabletFocalPoint: parseFocal("55% 48%"),
    mobileFocalPoint: parseFocal("55% 44%"),
    motionTreatment: "section-reveal",
    programme: "functional-training",
    replacementPriority: "P1",
  },
  {
    id: "programme-zumba-hero-ai-concept",
    slot: "programme.zumba.hero",
    ...ILLUSTRATIVE,
    kind: "image",
    src: "/media/synthetic-preview/programme-zumba-hero-v2.webp",
    width: 1200,
    height: 896,
    orientation: "landscape",
    aspectRatio: "4/3",
    mobileAspectRatio: "4/3",
    alt: "Illustrative Zumba group fitness dance session",
    focalPoint: parseFocal("50% 40%"),
    tabletFocalPoint: parseFocal("50% 40%"),
    mobileFocalPoint: parseFocal("50% 36%"),
    motionTreatment: "hero-reveal",
    programme: "zumba",
    replacementPriority: "P0",
  },
  {
    id: "programme-yoga-hero-ai-concept",
    slot: "programme.yoga.hero",
    ...ILLUSTRATIVE,
    kind: "image",
    src: "/media/synthetic-preview/programme-yoga-hero-v2-landscape.webp",
    width: 1200,
    height: 896,
    orientation: "landscape",
    aspectRatio: "4/3",
    mobileAspectRatio: "4/3",
    alt: "Illustrative yoga practice in a calm studio setting",
    focalPoint: parseFocal("50% 42%"),
    tabletFocalPoint: parseFocal("50% 42%"),
    mobileFocalPoint: parseFocal("50% 38%"),
    motionTreatment: "hero-reveal",
    programme: "yoga",
    replacementPriority: "P0",
  },
  {
    id: "programme-dance-hero-ai-concept",
    slot: "programme.dance.hero",
    ...ILLUSTRATIVE,
    kind: "image",
    src: "/media/synthetic-preview/programme-dance-hero-v2-landscape.webp",
    width: 1200,
    height: 896,
    orientation: "landscape",
    aspectRatio: "4/3",
    mobileAspectRatio: "4/3",
    alt: "Illustrative adult dance choreography in a studio room",
    focalPoint: parseFocal("50% 40%"),
    tabletFocalPoint: parseFocal("50% 40%"),
    mobileFocalPoint: parseFocal("50% 36%"),
    motionTreatment: "hero-reveal",
    programme: "adult-dance",
    replacementPriority: "P0",
  },
  {
    id: "programme-wedding-hero-ai-concept",
    slot: "programme.wedding.hero",
    ...ILLUSTRATIVE,
    kind: "image",
    src: "/media/synthetic-preview/programme-wedding-hero-v2.webp",
    width: 1024,
    height: 1024,
    orientation: "square",
    aspectRatio: "1/1",
    mobileAspectRatio: "1/1",
    alt: "Illustrative wedding choreography rehearsal with couple",
    focalPoint: parseFocal("50% 38%"),
    tabletFocalPoint: parseFocal("50% 38%"),
    mobileFocalPoint: parseFocal("50% 36%"),
    motionTreatment: "hero-reveal",
    programme: "wedding-choreography",
    replacementPriority: "P0",
  },
  {
    id: "programme-home-pt-hero-ai-concept",
    slot: "programme.home-pt.hero",
    ...ILLUSTRATIVE,
    kind: "image",
    src: "/media/synthetic-preview/programme-home-pt-hero-v2-landscape.webp",
    width: 1200,
    height: 896,
    orientation: "landscape",
    aspectRatio: "4/3",
    mobileAspectRatio: "4/3",
    alt: "Illustrative home personal training coaching session",
    focalPoint: parseFocal("50% 44%"),
    tabletFocalPoint: parseFocal("50% 44%"),
    mobileFocalPoint: parseFocal("50% 40%"),
    motionTreatment: "hero-reveal",
    programme: "home-personal-training",
    replacementPriority: "P1",
  },
  {
    id: "programme-online-hero-ai-concept",
    slot: "programme.online.hero",
    ...ILLUSTRATIVE,
    kind: "image",
    src: "/media/synthetic-preview/programme-online-hero-ai-concept.webp",
    width: 1536,
    height: 1168,
    orientation: "landscape",
    aspectRatio: "4/3",
    mobileAspectRatio: "4/3",
    alt: "Illustrative remote coaching session at home",
    focalPoint: parseFocal("68% 42%"),
    tabletFocalPoint: parseFocal("66% 44%"),
    mobileFocalPoint: parseFocal("70% 40%"),
    motionTreatment: "hero-reveal",
    programme: "online-training",
    replacementPriority: "P1",
  },
  {
    id: "programme-corporate-wellness-hero-ai-concept",
    slot: "programme.corporate-wellness.hero",
    ...ILLUSTRATIVE,
    kind: "image",
    src: "/media/synthetic-preview/programme-corporate-wellness-hero-v2-square.webp",
    width: 1024,
    height: 1024,
    orientation: "square",
    aspectRatio: "1/1",
    mobileAspectRatio: "1/1",
    alt: "Illustrative workplace wellness session with a coach guiding a small group",
    focalPoint: parseFocal("50% 44%"),
    tabletFocalPoint: parseFocal("50% 44%"),
    mobileFocalPoint: parseFocal("50% 40%"),
    motionTreatment: "hero-reveal",
    programme: "corporate-wellness",
    replacementPriority: "P1",
  },
  /* about-community-ai-concept removed — AI coaching-team image
     should not appear beside real "15+ coaches" messaging.
     Slot remains empty until real consented team photography. */
  {
    id: "locations-atmosphere-ai-concept",
    slot: "locations.atmosphere",
    ...ILLUSTRATIVE,
    kind: "image",
    src: "/media/synthetic-preview/locations-atmosphere-v2.webp",
    width: 1376,
    height: 768,
    orientation: "landscape",
    aspectRatio: "16/9",
    mobileAspectRatio: "2/1",
    alt: "Illustrative neighbourhood studio atmosphere — not a specific branch",
    focalPoint: parseFocal("50% 55%"),
    tabletFocalPoint: parseFocal("50% 55%"),
    mobileFocalPoint: parseFocal("50% 50%"),
    motionTreatment: "section-reveal",
    replacementPriority: "P2",
  },
] as const;

export function getCatalogueItem(slotKey: string): StudioMediaItem | undefined {
  return MEDIA_CATALOGUE.find((item) => item.slot === slotKey);
}
