import type { PremiumSlotDefinition } from "./types";

/**
 * Stage 4A high-value premium slots — extends (does not delete) legacy
 * `STUDIO_MEDIA_SLOTS` catalogue keys.
 */
export const PREMIUM_MEDIA_SLOTS: readonly PremiumSlotDefinition[] = [
  {
    key: "home.hero",
    purpose: "Immediate emotional proof of movement/energy",
    desktopAspect: "16/9",
    mobileAspect: "4/5",
    motionTreatment: "hero-reveal",
    replacementPriority: "P0",
    fallbackFamily: "strength",
    verifiedRealOnly: false,
    geometryPreview: true,
    compositionHint: "editorial-split",
  },
  {
    key: "home.community",
    purpose: "Group/community energy",
    desktopAspect: "16/9",
    mobileAspect: "3/2",
    motionTreatment: "section-reveal",
    replacementPriority: "P1",
    fallbackFamily: "warm",
    verifiedRealOnly: false,
    geometryPreview: true,
  },
  {
    key: "programme.functional.hero",
    purpose: "Functional Training programme hero",
    desktopAspect: "4/5",
    mobileAspect: "3/4",
    motionTreatment: "hero-reveal",
    replacementPriority: "P0",
    fallbackFamily: "strength",
    verifiedRealOnly: false,
    geometryPreview: true,
    programme: "functional-training",
    compositionHint: "structured",
  },
  {
    key: "programme.functional.action",
    purpose: "Functional Training secondary action",
    desktopAspect: "16/9",
    mobileAspect: "3/2",
    motionTreatment: "section-reveal",
    replacementPriority: "P1",
    fallbackFamily: "strength",
    verifiedRealOnly: false,
    geometryPreview: true,
    programme: "functional-training",
    compositionHint: "structured",
  },
  {
    key: "programme.zumba.hero",
    purpose: "Zumba programme hero",
    desktopAspect: "16/9",
    mobileAspect: "3/2",
    motionTreatment: "hero-reveal",
    replacementPriority: "P0",
    fallbackFamily: "high-energy",
    verifiedRealOnly: false,
    geometryPreview: true,
    programme: "zumba",
    compositionHint: "fluid",
  },
  {
    key: "programme.yoga.hero",
    purpose: "Yoga programme hero",
    desktopAspect: "4/5",
    mobileAspect: "4/5",
    motionTreatment: "hero-reveal",
    replacementPriority: "P0",
    fallbackFamily: "calm",
    verifiedRealOnly: false,
    geometryPreview: true,
    programme: "yoga",
    compositionHint: "calm",
  },
  {
    key: "programme.dance.hero",
    purpose: "Adult dance programme hero",
    desktopAspect: "4/5",
    mobileAspect: "3/4",
    motionTreatment: "hero-reveal",
    replacementPriority: "P0",
    fallbackFamily: "high-energy",
    verifiedRealOnly: false,
    geometryPreview: true,
    programme: "adult-dance",
    compositionHint: "expressive",
  },
  {
    key: "programme.wedding.hero",
    purpose: "Wedding choreography programme hero",
    desktopAspect: "4/5",
    mobileAspect: "4/5",
    motionTreatment: "hero-reveal",
    replacementPriority: "P0",
    fallbackFamily: "warm",
    verifiedRealOnly: false,
    geometryPreview: true,
    programme: "wedding-choreography",
    compositionHint: "ceremonial",
  },
  {
    key: "programme.home-pt.hero",
    purpose: "Home PT programme hero",
    desktopAspect: "4/5",
    mobileAspect: "3/4",
    motionTreatment: "hero-reveal",
    replacementPriority: "P1",
    fallbackFamily: "neutral",
    verifiedRealOnly: false,
    geometryPreview: true,
    programme: "home-personal-training",
    compositionHint: "direct",
  },
  {
    key: "programme.online.hero",
    purpose: "Online training programme hero",
    desktopAspect: "16/9",
    mobileAspect: "16/9",
    motionTreatment: "hero-reveal",
    replacementPriority: "P1",
    fallbackFamily: "neutral",
    verifiedRealOnly: false,
    geometryPreview: true,
    programme: "online-training",
    compositionHint: "remote",
  },
  {
    key: "programme.corporate-wellness.hero",
    purpose: "Corporate Wellness programme hero — illustrative workplace session",
    desktopAspect: "3/2",
    mobileAspect: "4/3",
    motionTreatment: "hero-reveal",
    replacementPriority: "P1",
    fallbackFamily: "neutral",
    verifiedRealOnly: false,
    geometryPreview: true,
    programme: "corporate-wellness",
    compositionHint: "direct",
  },
  {
    key: "about.community",
    purpose: "About community warmth",
    desktopAspect: "16/9",
    mobileAspect: "3/2",
    motionTreatment: "section-reveal",
    replacementPriority: "P1",
    fallbackFamily: "warm",
    verifiedRealOnly: false,
    geometryPreview: true,
  },
  {
    key: "about.founder",
    purpose: "Founder portrait — verified real only",
    desktopAspect: "4/5",
    mobileAspect: "3/4",
    motionTreatment: "static",
    replacementPriority: "P0",
    fallbackFamily: "warm",
    verifiedRealOnly: true,
    geometryPreview: false,
  },
  {
    key: "locations.atmosphere",
    purpose: "Generic conceptual studio atmosphere — not a named branch",
    desktopAspect: "16/9",
    mobileAspect: "3/2",
    motionTreatment: "section-reveal",
    replacementPriority: "P2",
    fallbackFamily: "neutral",
    verifiedRealOnly: false,
    geometryPreview: true,
    compositionHint: "atmosphere",
  },
  {
    key: "location.airoli-sector-19.hero",
    purpose: "Airoli Sector 19 branch hero — real media only",
    desktopAspect: "16/9",
    mobileAspect: "3/2",
    motionTreatment: "static",
    replacementPriority: "P0",
    fallbackFamily: "neutral",
    verifiedRealOnly: true,
    geometryPreview: false,
    branch: "airoli-sector-19",
  },
  {
    key: "location.airoli-sector-8.hero",
    purpose: "Airoli Sector 8 branch hero — real media only",
    desktopAspect: "16/9",
    mobileAspect: "3/2",
    motionTreatment: "static",
    replacementPriority: "P0",
    fallbackFamily: "neutral",
    verifiedRealOnly: true,
    geometryPreview: false,
    branch: "airoli-sector-8",
  },
  {
    key: "location.ghansoli.hero",
    purpose: "Ghansoli branch hero — real media only",
    desktopAspect: "16/9",
    mobileAspect: "3/2",
    motionTreatment: "static",
    replacementPriority: "P0",
    fallbackFamily: "neutral",
    verifiedRealOnly: true,
    geometryPreview: false,
    branch: "ghansoli",
  },
  {
    key: "location.thane.hero",
    purpose: "Thane branch hero — real media only",
    desktopAspect: "16/9",
    mobileAspect: "3/2",
    motionTreatment: "static",
    replacementPriority: "P0",
    fallbackFamily: "neutral",
    verifiedRealOnly: true,
    geometryPreview: false,
    branch: "thane",
  },
] as const;

export function getPremiumSlot(key: string): PremiumSlotDefinition | undefined {
  return PREMIUM_MEDIA_SLOTS.find((slot) => slot.key === key);
}

const PROGRAMME_HERO_SLOT: Record<string, string> = {
  "functional-training": "programme.functional.hero",
  zumba: "programme.zumba.hero",
  yoga: "programme.yoga.hero",
  "adult-dance": "programme.dance.hero",
  "wedding-choreography": "programme.wedding.hero",
  "home-personal-training": "programme.home-pt.hero",
  "online-training": "programme.online.hero",
  "corporate-wellness": "programme.corporate-wellness.hero",
};

export function programmeHeroSlotKey(slug: string): string | undefined {
  return PROGRAMME_HERO_SLOT[slug];
}
